In [2]:
import numpy as np, pandas as pd

## Numpy

1

In [3]:
numpy_array = np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

2

In [4]:
a = [1,2,3,4,5]
a_numpy = np.array(a)
a_numpy

array([1, 2, 3, 4, 5])

In [5]:
row_vector = a_numpy[:, np.newaxis]
row_vector

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
col_vector = a_numpy[np.newaxis, :]
col_vector

array([[1, 2, 3, 4, 5]])

In [7]:
a = np.arange(0,15) # got an error when using `range(0,15)`
b = a.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

3

In [8]:
a = [(1,2), [3,4,(5)], (6,7,8)]
b = np.asarray(a)
b

array([(1, 2), list([3, 4, 5]), (6, 7, 8)], dtype=object)

4

In [9]:
a =  np.zeros((3,4),dtype=np.float16)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

5

In [10]:
a = np.ones((3,4), dtype=np.int32)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

6

In [11]:
a = np.full((2,3),1,dtype=np.float16)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [12]:
x = np.empty((3,3),dtype=np.int16)
x

array([[257, 257, 257],
       [257, 257, 257],
       [257, 257, 257]], dtype=int16)

7

In [13]:
np.linspace(1,10,num=9,endpoint=False,retstep=True)

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

In [14]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

8

In [15]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

9

In [16]:
x = np.array([1,2,3])
x.ndim

1

10

In [17]:
x = np.ones((3,2,4), dtype=np.int16)
x.size

24

11

In [18]:
x.nbytes

48

12

In [19]:
x = np.ones((2,3), dtype=np.int16)
x.dtype

dtype('int16')

13

In [20]:
y = np.array([[1,3],[5,6]])
x = np.copy(y)

14

In [21]:
x = np.array([[1,2], [3,4]])
x.T

array([[1, 3],
       [2, 4]])

15

In [22]:
x = np.array([[1,2,3], [4,5,6]])
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [23]:
x.ravel()

array([1, 2, 3, 4, 5, 6])

16

In [24]:
x = np.ones((3,4,5))
np.moveaxis(x,[1], [2])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
x = np.array([[1,2], [3,4]])
x.shape
x

array([[1, 2],
       [3, 4]])

In [26]:
np.swapaxes(x,0,1)

array([[1, 3],
       [2, 4]])

17

In [27]:
x = np.array([[3,4,5,9], [2,6,8,0]])
y = x.tolist()
y

[[3, 4, 5, 9], [2, 6, 8, 0]]

18

In [28]:
x = np.array([0,1,2.0,3.0,4.2], dtype=np.float32)
x.astype(np.int16)

array([0, 1, 2, 3, 4], dtype=int16)

In [29]:
x.astype(np.bool)

array([False,  True,  True,  True,  True])

19

In [30]:
x = np.array([0,1,2.0,3.0,4.2], dtype=np.float32)
x.nonzero()

(array([1, 2, 3, 4], dtype=int64),)

In [31]:
x = np.array([[0,1], [3,5]])
x.nonzero()

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

20

In [32]:
x = np.array([[4,3], [3,2]])
x.sort(axis=1)
x

array([[3, 4],
       [2, 3]])

In [33]:
x = np.array([[4,3], [3,2]])
x.sort(axis=0)
x

array([[3, 2],
       [4, 3]])

21

In [34]:
x = np.array([[0,1],[2,3]])
x == 1

array([[False,  True],
       [False, False]])

In [35]:
(x==1).astype(np.int16).sum()

1

22

In [36]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [37]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [38]:
np.matmul(a,b)

array([[1., 2.],
       [3., 4.]])

23

In [39]:
a = np.array([[1,2,3], [4,8,16]])
b = np.array([5,6,11]).reshape(-1,1)

np.dot(a,b)

array([[ 50],
       [244]])

24

In [40]:
x = [1,2,3]
y = [4,5,6]

z = np.cross(x,y)
z

array([-3,  6, -3])

25

In [41]:
x = np.array([5,10,14,17,19,26])
np.gradient(x)

array([5. , 4.5, 3.5, 2.5, 4.5, 7. ])

26

In [43]:
x = np.array([[2,4,9], [3,1,5], [7,8,0]])

x[[0,0,2,2], [0,1,0,1]]

array([2, 4, 7, 8])

27

In [47]:
a = np.array([[3,5,8],[4,5,6],[9,7,2]])
b = np.array([2,3,4])

a + b

array([[ 5,  8, 12],
       [ 6,  8, 10],
       [11, 10,  6]])

## Pandas

1

In [48]:
df = pd.read_csv("imdb_ratings.csv")

2

In [49]:
c1, c2, c3, *rest = df.columns
d_dic = {'first_col_name':c1, 'second_col_names':c2, '3rd_col_name':c3}
new_df = pd.DataFrame(data = d_dic, index = [0])

np_data = np.zeros((3,3))

new_df = pd.DataFrame(data = np_data, columns = d_dic)

df.head()

Votes  Rank                       Title  Year  Decade
0   88355   8.4                    M (1931)  1931    1930
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980

3

In [50]:
df.head()
df.tail()

col = df.columns[0]

df[col].head(10)
df[col].tail(10)

240     117590
241      85012
242     476501
243     268905
244      69988
245    1078416
246      31003
247     167076
248      91689
249     589477
Name: Votes, dtype: int64

4

In [51]:
new_df = df.rename(columns = {'Votes':'Total Votes'})
new_df.head()

Total Votes  Rank                       Title  Year  Decade
0        88355   8.4                    M (1931)  1931    1930
1       132823   8.3  Singin' in the Rain (1952)  1952    1950
2        74178   8.3        All About Eve (1950)  1950    1950
3       635139   8.6                 Léon (1994)  1994    1990
4       145514   8.2     The Elephant Man (1980)  1980    1980

5

In [52]:
df.columns.tolist()

['Votes', 'Rank', 'Title', 'Year', 'Decade']

6

In [53]:
df["Year"].value_counts()
df["Year"].value_counts()[1995]

10

7

In [54]:
new_df = df.reset_index(drop=True, inplace=False)

8

In [55]:
df.drop(columns=["Year"]).head()

Votes  Rank                       Title  Decade
0   88355   8.4                    M (1931)    1930
1  132823   8.3  Singin' in the Rain (1952)    1950
2   74178   8.3        All About Eve (1950)    1950
3  635139   8.6                 Léon (1994)    1990
4  145514   8.2     The Elephant Man (1980)    1980

9

In [56]:
new_df = df.set_index("Year")
new_df.head()

Votes  Rank                       Title  Decade
Year                                                  
1931   88355   8.4                    M (1931)    1930
1952  132823   8.3  Singin' in the Rain (1952)    1950
1950   74178   8.3        All About Eve (1950)    1950
1994  635139   8.6                 Léon (1994)    1990
1980  145514   8.2     The Elephant Man (1980)    1980

10

In [57]:
df.dropna(axis=0, inplace=True)

11

In [58]:
mask = df['Year'] > 1970

result = df[mask]

result

mask = (df['Year'] > 1970) & (df['Rank'] > 8)

result2 = df[mask]

result2

Votes  Rank                                         Title  Year  Decade
3     635139   8.6                                   Léon (1994)  1994    1990
4     145514   8.2                       The Elephant Man (1980)  1980    1980
5     425461   8.3                      Full Metal Jacket (1987)  1987    1980
6     441174   8.1                              Gone Girl (2014)  2014    2010
7     850601   8.3                          Batman Begins (2005)  2005    2000
..       ...   ...                                           ...   ...     ...
242   476501   8.6                         Cidade de Deus (2002)  2002    2000
245  1078416   8.7                           Forrest Gump (1994)  1994    1990
247   167076   8.2                               3 Idiots (2009)  2009    2000
248    91689   8.1                                Network (1976)  1976    1970
249   589477   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004    2000

[137 rows x 5 columns]

12

In [59]:
df.iat[1,2]
df.at[0, "Year"]
df.loc[np.arange(0,5), ['Rank', 'Year']]
df.iloc[[0,2], [3,4]]

Year  Decade
0  1931    1930
2  1950    1950

13

In [60]:
sum_ranks = 0
for i, row in df.iterrows():
    sum_ranks+=row['Rank']
sum_ranks

for row in df.itertuples():
    print(row.Year)

1931
1952
1950
1994
1980
1987
2014
2005
1961
2014
1934
2008
1959
2009
1987
1997
1998
1939
1969
2006
1993
1940
1972
2003
2005
2009
2011
2011
1966
1973
2010
1975
1995
1968
2013
1956
1973
1962
1980
1967
2001
2015
1964
1984
2000
2007
2014
1991
2000
1927
1944
1953
2012
1994
2009
1979
2014
1966
1984
1963
1982
2010
1958
1979
2010
1950
1995
1960
2002
2000
2014
1975
1941
1982
1979
1948
2008
1954
1968
1995
2007
2010
1959
2004
1983
1991
1950
1999
1985
2004
2006
1974
1962
2014
1997
1986
1995
1991
1954
2001
2014
1939
1946
1990
1999
1957
2010
1988
2011
1985
2000
2003
2002
2012
1982
1999
1995
2003
1948
1955
1946
1976
2008
1993
1988
1957
1995
1984
1966
1999
1992
2011
1982
1998
1994
1959
1977
1966
1992
1995
1983
2003
2013
1988
2001
1962
1926
1993
2014
1999
2005
1986
2001
1965
1993
1998
1980
1971
1942
1996
1957
1997
1988
1996
2007
1954
1946
1940
2001
1995
1995
1952
2004
1921
2012
2006
1964
1954
2001
2001
1995
1986
1967
2009
2002
1959
1957
1978
1939
1977
2004
2010
1952
2013
1961
1958
1975
2006
2013
2007


14

In [61]:
df.sort_values(by = ["Year", "Rank"], ascending = True)

Votes  Rank                            Title  Year  Decade
173   55784   8.3                   The Kid (1921)  1921    1920
205   58506   8.2             The Gold Rush (1925)  1925    1920
146   46332   8.2               The General (1926)  1926    1920
49    98794   8.3                Metropolis (1927)  1927    1920
0     88355   8.4                         M (1931)  1931    1930
..      ...   ...                              ...   ...     ...
100  369141   8.1  The Grand Budapest Hotel (2014)  2014    2010
148  264333   8.5                  Whiplash (2014)  2014    2010
70   689541   8.6              Interstellar (2014)  2014    2010
233  262425   8.3        Mad Max: Fury Road (2015)  2015    2010
41    79615   8.5              Inside Out (2015/I)  2015    2010

[250 rows x 5 columns]

15

In [62]:
def minus_1(x):
    return x - 1
df["Year"].apply(minus_1)

df[["Year", "Rank"]].apply(minus_1)

Year  Rank
0    1930   7.4
1    1951   7.3
2    1949   7.3
3    1993   7.6
4    1979   7.2
..    ...   ...
245  1993   7.7
246  1952   7.1
247  2008   7.2
248  1975   7.1
249  2003   7.3

[250 rows x 2 columns]

16

In [63]:
def f(x):
    return type(x) 

new_df = df.applymap(f)

new_df.head()

Votes             Rank          Title           Year         Decade
0  <class 'int'>  <class 'float'>  <class 'str'>  <class 'int'>  <class 'int'>
1  <class 'int'>  <class 'float'>  <class 'str'>  <class 'int'>  <class 'int'>
2  <class 'int'>  <class 'float'>  <class 'str'>  <class 'int'>  <class 'int'>
3  <class 'int'>  <class 'float'>  <class 'str'>  <class 'int'>  <class 'int'>
4  <class 'int'>  <class 'float'>  <class 'str'>  <class 'int'>  <class 'int'>

17

In [64]:
df[df["Year"].isin([1970,1971,1972])]
df[~df["Year"].isin([1970,1971,1972])]

Votes  Rank                                         Title  Year  Decade
0      88355   8.4                                      M (1931)  1931    1930
1     132823   8.3                    Singin' in the Rain (1952)  1952    1950
2      74178   8.3                          All About Eve (1950)  1950    1950
3     635139   8.6                                   Léon (1994)  1994    1990
4     145514   8.2                       The Elephant Man (1980)  1980    1980
..       ...   ...                                           ...   ...     ...
245  1078416   8.7                           Forrest Gump (1994)  1994    1990
246    31003   8.1                  Le salaire de la peur (1953)  1953    1950
247   167076   8.2                               3 Idiots (2009)  2009    2000
248    91689   8.1                                Network (1976)  1976    1970
249   589477   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004    2000

[248 rows x 5 columns]

18

In [65]:
df.groupby(['Decade']).agg({'Rank':'mean'})
df.groupby(['Decade']).agg(list)

Votes  \
Decade                                                      
1920                         [98794, 46332, 55784, 58506]   
1930    [88355, 56842, 69510, 259235, 192791, 121668, ...   
1940    [55793, 86715, 101754, 71003, 35983, 81887, 66...   
1950    [132823, 74178, 156432, 56671, 87437, 65408, 9...   
1960    [37664, 134552, 32385, 373482, 170302, 108128,...   
1970    [1027398, 155691, 364225, 87591, 496833, 24288...   
1980    [145514, 425461, 264285, 532559, 43090, 195266...   
1990    [635139, 192165, 769893, 95212, 158867, 767224...   
2000    [850601, 502773, 755013, 229533, 55382, 700999...   
2010    [441174, 46987, 287727, 417122, 670328, 359121...   

                                                     Rank  \
Decade                                                      
1920                                 [8.3, 8.2, 8.3, 8.2]   
1930                  [8.4, 8.1, 8.2, 8.1, 8.1, 8.5, 8.5]   
1940    [8.1, 8.3, 8.1, 8.3, 8.1, 8.3, 8.0, 8.5, 8.0, ...   
1950    [8.3, 8.3, 8.3, 8.0, 8.0, 8.1, 8.3, 8.0, 8.4, ...   
1960    [8.2, 8.1, 8.0, 8.3, 8.3, 8.1, 8.5, 8.9, 8.2, ...   
1970    [9.2, 8.3, 8.0, 8.0, 8.5, 8.1, 8.0, 8.5, 9.0, ...   
1980    [8.2, 8.3, 8.1, 8.4, 8.0, 8.4, 8.1, 8.2, 8.4, ...   
1990    [8.6, 8.4, 8.5, 8.1, 8.0, 8.6, 9.2, 8.2, 8.3, ...   
2000    [8.3, 8.2, 8.3, 8.4, 8.0, 8.2, 8.1, 8.1, 8.3, ...   
2010    [8.1, 8.0, 8.2, 8.5, 8.1, 8.1, 8.5, 8.0, 8.2, ...   

                                                    Title  \
Decade                                                      
1920    [Metropolis (1927), The General (1926), The Ki...   
1930    [M (1931), It Happened One Night (1934), Mr. S...   
1940    [The Grapes of Wrath (1940), Double Indemnity ...   
1950    [Singin' in the Rain (1952), All About Eve (19...   
1960    [Judgment at Nuremberg (1961), Butch Cassidy a...   
1970    [The Godfather (1972), The Sting (1973), Jaws ...   
1980    [The Elephant Man (1980), Full Metal Jacket (1...   
1990    [Léon (1994), Mononoke-hime (1997), Saving Pri...   
2000    [Batman Begins (2005), Gran Torino (2008), Ing...   
2010    [Gone Girl (2014), Relatos salvajes (2014), Wa...   

                                                     Year  
Decade                                                     
1920                             [1927, 1926, 1921, 1925]  
1930           [1931, 1934, 1939, 1939, 1939, 1936, 1931]  
1940    [1940, 1944, 1941, 1948, 1946, 1948, 1946, 194...  
1950    [1952, 1950, 1959, 1956, 1953, 1958, 1950, 195...  
1960    [1961, 1969, 1966, 1968, 1962, 1967, 1964, 196...  
1970    [1972, 1973, 1975, 1973, 1979, 1979, 1975, 197...  
1980    [1980, 1987, 1987, 1980, 1984, 1984, 1982, 198...  
1990    [1994, 1997, 1998, 1993, 1995, 1991, 1994, 199...  
2000    [2005, 2008, 2009, 2006, 2003, 2005, 2009, 200...  
2010    [2014, 2014, 2011, 2011, 2010, 2013, 2015, 201...

19

In [66]:
agg_df = df.groupby(['Decade']).agg(list)
agg_df['Votes'].explode()

Decade
1920     98794
1920     46332
1920     55784
1920     58506
1930     88355
         ...  
2010    312516
2010    258882
2010    133760
2010    997350
2010    262425
Name: Votes, Length: 250, dtype: object

20

In [67]:
df1 = df
df2 = df

vertical = pd.concat([df1,df2], axis = 0)

vertical.head()

horiz = pd.concat([df1,df2], axis = 1)

horiz.head()

Votes  Rank                       Title  Year  Decade   Votes  Rank  \
0   88355   8.4                    M (1931)  1931    1930   88355   8.4   
1  132823   8.3  Singin' in the Rain (1952)  1952    1950  132823   8.3   
2   74178   8.3        All About Eve (1950)  1950    1950   74178   8.3   
3  635139   8.6                 Léon (1994)  1994    1990  635139   8.6   
4  145514   8.2     The Elephant Man (1980)  1980    1980  145514   8.2   

                        Title  Year  Decade  
0                    M (1931)  1931    1930  
1  Singin' in the Rain (1952)  1952    1950  
2        All About Eve (1950)  1950    1950  
3                 Léon (1994)  1994    1990  
4     The Elephant Man (1980)  1980    1980

21

In [68]:
df1.merge(df2, on=["Title"], how="inner")

Votes_x  Rank_x                                         Title  Year_x  \
0      88355     8.4                                      M (1931)    1931   
1     132823     8.3                    Singin' in the Rain (1952)    1952   
2      74178     8.3                          All About Eve (1950)    1950   
3     635139     8.6                                   Léon (1994)    1994   
4     145514     8.2                       The Elephant Man (1980)    1980   
..       ...     ...                                           ...     ...   
245  1078416     8.7                           Forrest Gump (1994)    1994   
246    31003     8.1                  Le salaire de la peur (1953)    1953   
247   167076     8.2                               3 Idiots (2009)    2009   
248    91689     8.1                                Network (1976)    1976   
249   589477     8.3  Eternal Sunshine of the Spotless Mind (2004)    2004   

     Decade_x  Votes_y  Rank_y  Year_y  Decade_y  
0        1930    88355     8.4    1931      1930  
1        1950   132823     8.3    1952      1950  
2        1950    74178     8.3    1950      1950  
3        1990   635139     8.6    1994      1990  
4        1980   145514     8.2    1980      1980  
..        ...      ...     ...     ...       ...  
245      1990  1078416     8.7    1994      1990  
246      1950    31003     8.1    1953      1950  
247      2000   167076     8.2    2009      2000  
248      1970    91689     8.1    1976      1970  
249      2000   589477     8.3    2004      2000  

[250 rows x 9 columns]

* What are some useful things you can you do with numpy and pandas?
    * Mass transforms on values in a dataframe.
    * Generating random data.
    * Merging, sorting and aggregating data.
    * Slicing and filtering data.
    * Generating statistics on data.
    * Reshaping data.
    * Sophisticated value transforms using functions and the pandas `apply` function.
* Why would those useful things be helpful in data analysis?
    * The data a data scientist will consume will rarely be perfectly formatted. Alot of the tools numpy and pandas provide can help one transform the data into output for other programs. 
    * One role of a data scientist is to think about data in different ways and numpy and pandas have multiple tools that can provide new insights into the data.
* What challenges did you have in following the examples?
    * I find it challening at times to reshape data, especially multidimensional data. I had to re-read the `swapaxes` function a few times to understand its purpose. It's still unclear right now how I would use the `reshape` and `swapaxes` functions.
    * The `gradient`, and `cross` functions are new to me and I don't know how to use them correctly.